---

- hosts: all
  become: true
  pre_tasks:

    - name: install updates (CentOS)
      tags: always
      dnf:
        update_only: yes
        update_cache: yes
      when: ansible_distribution == "CentOS"
      
    - name: install updates (Ubuntu)
      tags: always
      apt:
        upgrade: dist
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

- hosts: web_servers
  become: true
  tasks:
      
    - name: install apache and php packages (CentOS)
      tags: apache,centos,httpd
      dnf:
        name:
          - httpd
          - php
        state: latest
      when: ansible_distribution == "CentOS"

    - name: install apache2 and php packages (Ubuntu)
      tags: apache,apache2,ubuntu
      apt:
        name:
          - apache2
          - libapache2-mod-php
        state: latest
      when: ansible_distribution == "Ubuntu"

    - name: copy html file for the site
      tags: apache,apache2,httpd
      copy:
        src: default_site.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: 0644 # allows you to read and write to a file or directory and other users can only read it.

- hosts: db_servers
  become: true
  tasks:

    - name: install mariadb package (CentOS)
      tags: centos,db,mariadb
      dnf:
        name: mariadb
        state: latest
      when: ansible_distribution == "CentOS"

    - name: install mariadb server package (Ubuntu)
      tags: db,mariadb,ubuntu
      apt:
        name: mariadb-server
        state: latest
      when: ansible_distribution == "Ubuntu"

- hosts: file_servers
  become: true
  tasks:

    - name: install samba package
      tags: samba
      package:
        name: samba
        state: latest

- hosts: nginx_servers
  become: true
  vars:
    home_path: "/home/sage"
  tasks:

    - name: install dependencies
      dnf:
        name:
          - gcc
          - make
          - pcre2-devel
          - zlib-devel
          - openssl-devel
        state: latest
      when: ansible_distribution == "CentOS"

    - name: create nginx directory
      file:
        path: "{{ home_path }}/nginx-1.28.0"
        state: directory
        mode: "0755"
      when: ansible_distribution == "CentOS"

    - name: extract Nginx source code
      unarchive:
        src: https://github.com/nginx/nginx/releases/download/release-1.28.0/nginx-1.28.0.tar.gz
        dest: "{{ home_path }}"
        remote_src: yes
      when: ansible_distribution == "CentOS"

    - name: run configure script
      shell: ./configure
      args:
        chdir: "{{ home_path }}/nginx-1.28.0"
      when: ansible_distribution == "CentOS"

    - name: build the default target
      make:
        chdir: "{{ home_path }}/nginx-1.28.0"
      when: ansible_distribution == "CentOS"

    - name: run 'install' target as root
      make:
        chdir: "{{ home_path }}/nginx-1.28.0"
        target: install
        params:
          NUM_THREADS: 2
      become: yes
      when: ansible_distribution == "CentOS"

